<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Helpdesk.SLA.Domain\Helpdesk.SLA.Domain.csproj" />
    <ProjectReference Include="..\..\Tickets\Helpdesk.Tickets.Domain\Helpdesk.Tickets.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
